### PR TITLE
Bump displaylink to latest upstream 1.2

### PR DESCRIPTION
**Pull request by ssaavedra**

### CODE REVIEW

**Comment by ssaavedra** [comment]
This is a request for comments, for the moment. If merged as is, the package would not be buildable. Latest displaylink decompresses several folders, and not only x86 and x64; now there are:

- x64-ubuntu-1404
- x64-ubuntu-1604
- x86-ubuntu-1404
- x86-ubuntu-1604

Which should we be using for Fedora, and how are they different?

**Comment by waterfoul** [comment]
I believe we want the ubuntu-1604 ones as that should be on the latest kernel, they probably made the split because they had to make a backwards incompatible change to the sources because of the header changes

**Comment by waterfoul** [comment]
So I just tried this and the display adapters register and activate but i'm sitting with black screens....

**Comment by waterfoul** [comment]
I just tried with the 4.7 kernel and it does work! Here's the diff to bring your branch up to my system

diff --git a/displaylink.spec b/displaylink.spec
index 3bfffcb..8f4489a 100644
--- a/displaylink.spec
+++ b/displaylink.spec
@@ -17,7 +17,7 @@ Source4:      DisplayLink USB Graphics Software for Ubuntu 1.2.zip
 ExclusiveArch: i386 x86_64
 
 BuildRequires: libdrm-devel
-Requires:      dkms, kernel > 3.14, kernel-devel > 3.14
+Requires:      dkms, kernel > 4.7, kernel-devel > 4.7
 
 %description
 This adds support for HDMI/VGA adapters built upon the DisplayLink DL-5xxx,
@@ -67,11 +67,11 @@ cd evdi-%{version}/displaylink-driver-%{daemon_version}
 cp LICENSE ../..
 
 %ifarch x86_64
-cp -a x64/DisplayLinkManager $RPM_BUILD_ROOT/usr/libexec/displaylink/
+cp -a x64-ubuntu-1604/DisplayLinkManager $RPM_BUILD_ROOT/usr/libexec/displaylink/
 %endif
 
 %ifarch %ix86
-cp -a x86/DisplayLinkManager $RPM_BUILD_ROOT/usr/libexec/displaylink/
+cp -a x86-ubuntu-1604/DisplayLinkManager $RPM_BUILD_ROOT/usr/libexec/displaylink/
 %endif
 
 # Firmwares

**Comment by ssaavedra** [comment]
Patch applied

**Comment by hadess** [comment]
@ssaavedra I don't actually use those drivers nowadays, do you want to start maintaining this repository?

**Comment by ssaavedra** [comment]
I don't mind, for as long as I still use them :-)

Out of curiosity, did you stop using them because you no longer use the hardware or are there any other drivers available?

**Comment by hadess** [comment]
I never actually used them for more than an afternoon. The dock has HDMI input, and that's what I used then and now.

I've added you to the project, so anything you can test, shipping binary RPMs, etc. just go ahead. Let me know if you need any help.

**Comment by ssaavedra** [comment]
> The dock has HDMI input, and that's what I used then and now.

You mean HDMI output?

Are you referring to D-3100 or to some other hardware? I was unable to use it via anything different than DisplayLink.

And thanks for the access and help.

**Comment by hadess** [comment]
No, HDMI input, it's a Dell S2340T, a touchscreen with a USB dock.

**Comment by ssaavedra** [comment]
Ah, I see. Well, then I'll try to maintain this for at least as long as I use it to support the Dell D3100 : )

**Pull request merged**
